name: Elipsisize
favicon: null
layout_spectrum: 0.976304340409115
typography_spectrum: 0.8922765755560249
title: Introduction to Elipsisize
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4bea5'
    - '#e4eaea'
    - '#161b34'
    - '#646158'
    - '#b39c85'
  brandStrength: 0.9498739193659276
  lightness: 0.2144123138859868
  saturation: 0.9157859184779227
  rhythmicContrast: 0.4188439834397286
purpose: []
